import { z } from "zod";
export const MEALSCOUT_RO_CORE_PIN = {
  package: "@tradescout-infinity/reverse-osmosis", version: "0.1.0",
  sourceRevision: "b5cdef4187b9e21981c7bf004fb15fd34edd73cf",
  coreSha256: "ec55ed710765928b639f6be96b52379b45f5849b54f4396ff67c7e47f0a7fcd6",
} as const;
const id = z.string().min(1).max(512);
const hash = z.string().regex(/^[a-f0-9]{64}$/);
export const reverseOsmosisScopeSchema = z.object({ product: z.literal("mealscout"), businessId: id, ownerId: id, tenantId: z.literal("mealscout"), subjectId: id, provider: z.literal("facebook"), accountId: id }).strict();
const jsonValue: z.ZodType<any> = z.lazy(() => z.union([z.null(), z.boolean(), z.number().finite(), z.string().max(16384), z.array(jsonValue).max(4096), z.record(jsonValue)]));
export const reverseOsmosisProposalSchema = z.object({ scope: reverseOsmosisScopeSchema, direction: z.enum(["social-to-native", "native-to-social"]), eventId: id, sourceVersion: id, expectedNativeVersion: hash, fields: z.record(jsonValue), causalProvenance: id.optional(), businessBindingRevision: id, payloadDigest: hash, operationKey: hash }).strict();
export const reverseOsmosisCaptureSchema = z.object({ sourceUrl: z.string().url().max(2000), capturedAt: z.number().int().positive(), expiresAt: z.number().int().positive(), sourceVersion: hash, providerPostId: id, providerCreatedAt: z.string().nullable().optional(), providerUpdatedAt: z.string().nullable().optional(), bodyHash: hash, publicProofHash: hash, profile: z.object({ menuUrl: z.string().url().max(2000).optional() }).strict(), holds: z.array(z.string().max(1000)).max(50) }).strict();
export const reverseOsmosisEnvelopeSchema = z.object({ schemaVersion: z.literal("mealscout.reverse-osmosis.v1"), core: z.object({ package: z.literal(MEALSCOUT_RO_CORE_PIN.package), version: z.literal(MEALSCOUT_RO_CORE_PIN.version), sourceRevision: z.literal(MEALSCOUT_RO_CORE_PIN.sourceRevision), coreSha256: z.literal(MEALSCOUT_RO_CORE_PIN.coreSha256) }).strict(), capture: reverseOsmosisCaptureSchema, inbound: reverseOsmosisProposalSchema, outbound: z.array(reverseOsmosisProposalSchema).max(1) }).strict();
export type MealScoutReverseOsmosisEnvelope = z.infer<typeof reverseOsmosisEnvelopeSchema>;
// The native Zod schema and core perform semantic validation; MCP sees the same structural envelope.
const stringSchema = { type: "string", minLength: 1, maxLength: 512 };
const hashSchema = { type: "string", pattern: "^[a-f0-9]{64}$" };
const scope = { type: "object", additionalProperties: false, required: ["product","businessId","ownerId","tenantId","subjectId","provider","accountId"], properties: { product: { const: "mealscout" }, businessId: stringSchema, ownerId: stringSchema, tenantId: { const: "mealscout" }, subjectId: stringSchema, provider: { const: "facebook" }, accountId: stringSchema } };
const proposal = { type: "object", additionalProperties: false, required: ["scope","direction","eventId","sourceVersion","expectedNativeVersion","fields","businessBindingRevision","payloadDigest","operationKey"], properties: { scope, direction: { enum: ["social-to-native","native-to-social"] }, eventId: stringSchema, sourceVersion: stringSchema, expectedNativeVersion: hashSchema, fields: { type: "object" }, causalProvenance: stringSchema, businessBindingRevision: stringSchema, payloadDigest: hashSchema, operationKey: hashSchema } };
export const MEALSCOUT_RO_JSON_SCHEMA = { type: "object", additionalProperties: false, required: ["schemaVersion","core","capture","inbound","outbound"], properties: { schemaVersion: { const: "mealscout.reverse-osmosis.v1" }, core: { type: "object", additionalProperties: false, required: Object.keys(MEALSCOUT_RO_CORE_PIN), properties: Object.fromEntries(Object.entries(MEALSCOUT_RO_CORE_PIN).map(([key,value]) => [key,{ const: value }])) }, capture: { type: "object", additionalProperties: false, required: ["sourceUrl","capturedAt","expiresAt","sourceVersion","providerPostId","bodyHash","publicProofHash","profile","holds"], properties: { sourceUrl: { type: "string", format: "uri", maxLength: 2000 }, capturedAt: { type: "integer", minimum: 1 }, expiresAt: { type: "integer", minimum: 1 }, sourceVersion: hashSchema, providerPostId: stringSchema, providerCreatedAt: { type: ["string","null"] }, providerUpdatedAt: { type: ["string","null"] }, bodyHash: hashSchema, publicProofHash: hashSchema, profile: { type: "object", additionalProperties: false, properties: { menuUrl: { type: "string", format: "uri", maxLength: 2000 } } }, holds: { type: "array", maxItems: 50, items: { type: "string", maxLength: 1000 } } } }, inbound: proposal, outbound: { type: "array", maxItems: 1, items: proposal } } };
