import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { getTableColumns, getTableName, eq } from "drizzle-orm";
import bcrypt from "bcryptjs";
import * as schema from "../shared/schema";
import { readOwnerAiCapabilities, previewOwnerAiPacket } from "../shared/ownerAiCapabilities";
import { ownerAiActionPacketSchema } from "../shared/ownerAiActions";

// No network/production database: replace only the canonical db module in this process.
delete process.env.DATABASE_URL;
process.env.NODE_ENV = "development";
process.env.OWNER_AI_OAUTH_SECRET = "disposable-local-consent-fixture-000000000000";
let networkCalls = 0;
globalThis.fetch = async () => { networkCalls++; throw new Error("Settings-only fixture forbids network"); };
const engine = new PGlite();
const tables = [schema.users, schema.restaurants, schema.apiKeys, schema.ownerAiActionDrafts, schema.menus, schema.menuCategories, schema.menuItems, schema.truckManualSchedules, schema.foodBusinessAppearances, schema.deals, schema.socialPostQueue, schema.socialPublishingConnections, schema.telemetryEvents];
for (const table of tables) {
  const columns = Object.values(getTableColumns(table));
  await engine.exec(`create table "${getTableName(table)}" (${columns.map(c => `"${c.name}" ${/^(varchar|text|boolean|timestamp|integer|numeric|json|serial|double|real|bigint)/.test(c.getSQLType()) ? c.getSQLType() : "text"} ${c.name === "id" ? "primary key default gen_random_uuid()" : ""}`).join(",")})`);
}
const database = drizzle(engine);
(globalThis as any).__ownerAiFixtureDb = database;
registerHooks({ load(url, context, nextLoad) {
  if (/\/server\/db\.ts(?:\?|$)/.test(url)) return { format: "module", source: "export const db = globalThis.__ownerAiFixtureDb; export const pool = undefined;", shortCircuit: true };
  return nextLoad(url, context);
}});
const actions = await import("../server/services/ownerAiActions");
const { handleOwnerAiMcpRequest } = await import("../server/services/ownerAiMcp");
const token = "disposable_fixture_token_owner_123456789";
const settings = { platforms: { facebook: false, instagram: true, internal: "keep" }, triggers: { schedule: false, booking: true }, promptBeforePost: true, evidenceApply: { privateSource: "never expose", decisions: ["keep"] }, privateSettings: { x: 1 }, publicActionLinks: { menuUrl: "https://example.com/menu" }, publicGalleryImages: [{ id: "keep" }] };
await database.insert(schema.users).values({ id: "fixture-owner", isDisabled: false });
await database.insert(schema.restaurants).values({ id: "fixture-business", name: "Fixture", ownerId: "fixture-owner", businessType: "food_truck", socialAutopostSettings: settings, updatedAt: new Date() });
await database.insert(schema.apiKeys).values({ id: "fixture-key", userId: "fixture-owner", restaurantId: "fixture-business", keyPrefix: token.slice(0,8), keyHash: await bcrypt.hash(token, 4), purpose: "owner_ai_connector", scope: "owner_ai:context owner_ai:drafts:create owner_ai:drafts:read owner_ai:drafts:approve", isActive: true });
let principal = await actions.authenticateOwnerAiConnector(token, "owner_ai:context");
let seq = 1;
const call = async (name: string, args: any) => {
  const response: any = await handleOwnerAiMcpRequest(principal, { jsonrpc: "2.0", id: seq++, method: "tools/call", params: { name, arguments: args } });
  return response.result;
};
const success = (result: any) => { assert.equal(result.isError, undefined, JSON.stringify(result)); return result.structuredContent; };
const packet = { intent: "Review social preferences", settings: { socialPosting: { platforms: { facebook: true }, triggers: { live: true }, promptBeforePost: false } } };
let nextKey = 1;
const draft = async () => {
  const context = await actions.getOwnerAiContext(principal.restaurantId);
  const contextJson = JSON.stringify(context);
  assert.ok(!contextJson.includes("never expose")); assert.ok(!contextJson.includes('"internal"'));
  return success(await call("create_mealscout_draft", { idempotencyKey: `fixture-${nextKey++}`, request: { packet, expectedVersions: context.expectedVersions } }));
};
const prepare = async (d: any) => success(await call("prepare_mealscout_approval", { draftId: d.id }));
const approve = (d: any, consent: any, revision = d.revision) => call("approve_mealscout_draft", { draftId: d.id, expectedRevision: revision, consentHandle: consent.consentHandle, ownerConfirmation: "approved" });
const errorCode = (result: any, expected: string) => { assert.equal(result.isError, true); assert.ok(JSON.stringify(result).includes(expected), JSON.stringify(result)); };
try {
  for (const bad of [{}, { socialPosting: {} }, { socialPosting: { platforms: {} } }, { socialPosting: { triggers: { unknown: true } } }, { socialPosting: { evidenceApply: {} } }, { other: true }, { socialPosting: { promptBeforePost: "false" } }]) assert.equal(ownerAiActionPacketSchema.safeParse({ intent: "Invalid", settings: bad }).success, false);
  const emptyChecks = success(await call("get_mealscout_public_source_checks", {}));
  assert.deepEqual(emptyChecks.checks, []); assert.equal(emptyChecks.mutationPerformed, false);
  const { sourceCheckId, PUBLIC_SOURCE_CHECK_EVENT } = await import("../server/services/publicProfileSourceChecks");
  await database.insert(schema.telemetryEvents).values({ id: sourceCheckId(principal.restaurantId, "2026-09-30"), eventName: PUBLIC_SOURCE_CHECK_EVENT, properties: { version: 1, restaurantId: principal.restaurantId, ownerId: principal.userId, day: "2026-09-30", complete: true, outcome: "UNVERIFIED", publishes: false, verifiesFacts: false, receipts: [{ sourceUrl: "https://private.example/hidden", outcome: "UNVERIFIED", privateEvidence: "do not disclose" }] }, createdAt: new Date() });
  const seededChecks = success(await call("get_mealscout_public_source_checks", {}));
  assert.equal(seededChecks.checks.length, 1); assert.deepEqual(seededChecks.checks[0].receipts, []);
  assert.ok(!JSON.stringify(seededChecks).includes("private.example"));
  errorCode(await call("get_mealscout_public_source_checks", { restaurantId: "other" }), "MCP_TOOL_ARGUMENTS_INVALID");
  const originalPrincipal = principal;
  principal = { ...principal, scopes: [] }; errorCode(await call("get_mealscout_public_source_checks", {}), "CONNECTOR_SCOPE_REQUIRED"); principal = originalPrincipal;
  await database.update(schema.apiKeys).set({ revokedAt: new Date() }).where(eq(schema.apiKeys.id, principal.apiKeyId));
  errorCode(await call("get_mealscout_public_source_checks", {}), "PRINCIPAL_INACTIVE");
  await database.update(schema.apiKeys).set({ revokedAt: null }).where(eq(schema.apiKeys.id, principal.apiKeyId));
  console.log("PASS authenticated MCP source-check private receipts, empty/read-only result, missing scope, revoked credential, cross-business arguments rejected");
  const d = await draft(); const p = await prepare(d);
  assert.deepEqual(p.currentSnapshot.settings.effectiveSocialPosting.platforms, { facebook: true, instagram: true, x: true });
  assert.match(p.currentSnapshot.settings.warning, /without prompting/);
  assert.ok(!JSON.stringify(p).includes("never expose"));
  assert.match(p.consentPrompt, /without prompting/);
  assert.match(p.consentPrompt, /Effective social preferences/);
  assert.deepEqual(p.normalizedPlan[0].review, p.currentSnapshot.settings);
  errorCode(await call("approve_mealscout_draft", { draftId: d.id, expectedRevision: d.revision, consentHandle: p.consentHandle }), "EXPLICIT_OWNER_CONSENT_REQUIRED");
  const result = success(await approve(d,p)); assert.equal(result.canonicalCommitted, true);
  const [persisted] = await database.select().from(schema.restaurants).where(eq(schema.restaurants.id, principal.restaurantId));
  assert.deepEqual(persisted.socialAutopostSettings, { ...settings, platforms: { ...settings.platforms, facebook: true }, triggers: { ...settings.triggers, live: true }, promptBeforePost: false });
  assert.equal((await database.select().from(schema.socialPostQueue)).length, 0);
  console.log("PASS authenticated connector -> MCP create -> exact prepare -> explicit consent -> canonical persisted nested preferences; no social queue");
  for (const type of ["restaurant", "food_truck", "bar", "caterer", "private_chef"]) {
    await database.update(schema.restaurants).set({ businessType: type, updatedAt: new Date() }).where(eq(schema.restaurants.id, principal.restaurantId));
    const typed = await draft(); success(await approve(typed, await prepare(typed)));
  }
  await database.update(schema.restaurants).set({ businessType: "supplier" }).where(eq(schema.restaurants.id, principal.restaurantId));
  errorCode(await call("create_mealscout_draft", { idempotencyKey: "unsupported-type", request: { packet } }), "UNSUPPORTED_ADAPTER");
  await database.update(schema.restaurants).set({ businessType: "food_truck" }).where(eq(schema.restaurants.id, principal.restaurantId));
  const [beforeSparse] = await database.select().from(schema.restaurants).where(eq(schema.restaurants.id, principal.restaurantId));
  await database.update(schema.restaurants).set({ socialAutopostSettings: {} }).where(eq(schema.restaurants.id, principal.restaurantId));
  const sparseContext = await actions.getOwnerAiContext(principal.restaurantId);
  const sparse = success(await call("create_mealscout_draft", { idempotencyKey: "sparse-counterexample", request: { packet: { intent: "Future posting consent", settings: { socialPosting: { promptBeforePost: false } } }, expectedVersions: sparseContext.expectedVersions } }));
  const sparseP = await prepare(sparse);
  assert.deepEqual(sparseP.currentSnapshot.settings.effectiveSocialPosting.platforms, { facebook: true, instagram: true, x: true });
  assert.deepEqual(sparseP.currentSnapshot.settings.effectiveSocialPosting.triggers, { schedule: true, booking: true, live: true, deal: true });
  assert.deepEqual(sparseP.currentSnapshot.settings.effectiveSocialPosting.postingFlows, { schedule: "client_owner_schedule_save", booking: "client_owner_booking_action", live: "client_owner_live_location_action", deal: "server_deal_creation" });
  assert.match(sparseP.consentPrompt, /"facebook":true/); assert.match(sparseP.consentPrompt, /without prompting/);
  assert.match(sparseP.consentPrompt, /schedule, booking, and live-location/);
  assert.match(sparseP.consentPrompt, /native deal creation/);
  success(await approve(sparse,sparseP));
  const [sparseApplied] = await database.select().from(schema.restaurants).where(eq(schema.restaurants.id, principal.restaurantId));
  assert.deepEqual(sparseApplied.socialAutopostSettings, { promptBeforePost: false }, "Preview defaults must not become stored writes");
  await database.update(schema.restaurants).set({ socialAutopostSettings: beforeSparse.socialAutopostSettings }).where(eq(schema.restaurants.id, principal.restaurantId));
  const current = await actions.getOwnerAiContext(principal.restaurantId);
  const target = { profileType: "truck", profileId: principal.restaurantId };
  const now = new Date().toISOString();
  const authority = { target, currentOwnerId: principal.userId, adapter: "truck_native", backingRestaurantId: principal.restaurantId, currentVersions: current.expectedVersions, completeProfileAccess: true, provenance: { source: "native", access: "private", observedAt: now, expiresAt: null } };
  const capPrincipal = { apiKeyId: principal.apiKeyId, userId: principal.userId, scopes: principal.scopes, target, isActive: true, revokedAt: null, expiresAt: null };
  const input = { target, authority, principal: capPrincipal, now };
  const cap = readOwnerAiCapabilities(input);
  assert.equal(cap.profiles.find(p => p.profileType === "truck")!.settings, true);
  assert.ok(cap.profiles.filter(p => p.profileType !== "truck").every(p => !p.settings));
  const request = { packet, expectedVersions: current.expectedVersions, provenance: authority.provenance };
  assert.equal(previewOwnerAiPacket({ ...input, request }).canApply, false);
  assert.throws(() => previewOwnerAiPacket({ ...input, authority: { ...authority, completeProfileAccess: false }, request }), (e:any) => e.code === "COMPLETE_PROFILE_ACCESS_REQUIRED");
  const altered = await draft(); const alteredP = await prepare(altered);
  await database.update(schema.ownerAiActionDrafts).set({ normalizedPlan: [{ changed: true }] }).where(eq(schema.ownerAiActionDrafts.id, altered.id));
  errorCode(await approve(altered,alteredP), "OWNER_CONSENT_HANDLE_STALE");
  const stale = await draft(); const staleP = await prepare(stale);
  await database.update(schema.restaurants).set({ name: "Changed", updatedAt: new Date(Date.now()+1000) }).where(eq(schema.restaurants.id, principal.restaurantId));
  errorCode(await approve(stale,staleP), "STALE_CONTEXT");
  const rev = await draft(); const revP = await prepare(rev);
  await database.update(schema.ownerAiActionDrafts).set({ revision: 2 }).where(eq(schema.ownerAiActionDrafts.id, rev.id));
  errorCode(await approve(rev,revP), "STALE_DRAFT_REVISION");
  const denied = await draft(); const deniedP = await prepare(denied);
  await database.update(schema.users).set({ isDisabled: true }).where(eq(schema.users.id, principal.userId));
  errorCode(await approve(denied,deniedP), "COMPLETE_PROFILE_ACCESS_REQUIRED");
  const disabledCaps = success(await call("get_mealscout_profile_capabilities", {}));
  assert.ok(disabledCaps.profiles.every((p:any) => !p.settings));
  errorCode(await call("create_mealscout_draft", { idempotencyKey: "disabled-creation", request: { packet } }), "COMPLETE_PROFILE_ACCESS_REQUIRED");
  await database.delete(schema.users).where(eq(schema.users.id, principal.userId));
  errorCode(await approve(denied,deniedP), "COMPLETE_PROFILE_ACCESS_REQUIRED");
  errorCode(await call("create_mealscout_draft", { idempotencyKey: "denied-creation", request: { packet } }), "COMPLETE_PROFILE_ACCESS_REQUIRED");
  await database.insert(schema.users).values({ id: principal.userId, isDisabled: false });
  const transfer = await draft(); const transferP = await prepare(transfer);
  await database.update(schema.restaurants).set({ ownerId: "new-owner" }).where(eq(schema.restaurants.id, principal.restaurantId));
  await assert.rejects(actions.authenticateOwnerAiConnector(token), (e:any)=>e.code==="CONNECTOR_OWNERSHIP_INVALID");
  errorCode(await approve(transfer,transferP), "ACTUAL_OWNER_REQUIRED");
  assert.equal(networkCalls, 0);
  console.log("PASS five native food types, unsupported type rejection, private settings preview bounds, exact fingerprint consent, and zero network effects");
  console.log("PASS stale native versions, stale draft revision, denied create/apply access, ownership transfer all fail closed");
  assert.equal((await database.select().from(schema.socialPostQueue)).length, 0);
} finally { await engine.close(); }

